"""End-to-end proof that the whole platform works.

Every stage of the system is exercised against the real services and asserted on:

    1  configuration resolves
    2  ONNX embedding model loads and discriminates
    3  OpenSearch reachable, index present
    4  Tika extracts text with page structure
    5  OCR service reachable
    6  ingest: extract -> chunk -> embed -> index
    7  retrieval: BM25, kNN, RRF fusion, filters
    8  generation: grounded answer with citations
    9  OCR end-to-end: a page with NO text layer is read and becomes searchable
   10  HTTP API: /health, /config, /search, /ingest, and SSE /chat/stream

Exit code is 0 only if every stage passes, so it works as a CI gate.

    python ops/smoke_test.py                      # everything except the HTTP layer
    python ops/smoke_test.py --api-url http://localhost:8000   # + stage 10
    python ops/smoke_test.py --skip-llm           # no model endpoint needed
    python ops/smoke_test.py --skip-ocr           # OCR service not running
    python ops/smoke_test.py --keep               # leave test docs indexed
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "packages" / "rag_core" / "src"))

from rag_core.config import get_settings           # noqa: E402
from rag_core.documents import stable_id           # noqa: E402

GREEN, RED, YELLOW, CYAN, DIM, RESET = (
    "\033[32m", "\033[31m", "\033[33m", "\033[36m", "\033[2m", "\033[0m"
)

# Deliberately contains specific, checkable facts. A vague document cannot prove
# retrieval worked -- "the answer looks plausible" is not a test.
TEST_DOCUMENT = """\
Acme Corporation Records Retention Policy

Section 1. Purpose
This policy establishes how long Acme Corporation retains business records.

Section 2. Retention Periods
Claims documentation must be retained for seven years from the date of closure.
Payroll records must be retained for four years.
Board meeting minutes must be retained permanently.

Section 3. Escalation
Questions about destruction of records must be escalated to the Records
Custodian, currently reachable at extension 4471, before any disposal occurs.

Section 4. Exceptions
A legal hold suspends all retention limits until the hold is formally released
by the Office of General Counsel.
"""

TEST_FILENAME = "smoke-test-retention-policy.txt"
TEST_URI = "smoke-test://retention-policy"
QUESTION = "How long must claims documentation be retained?"
EXPECTED_IN_CONTEXT = "seven years"

# The OCR fixture, generated by ops/make_scan_fixture.py. No text layer at all.
OCR_FIXTURE = REPO_ROOT / "deploy" / "fixtures" / "scanned-facilities-policy.png"
OCR_URI = "smoke-test://scanned-facilities-policy"
OCR_QUESTION = "How long do badge replacement requests take?"
# OCR output is never character-perfect, so assert on a distinctive token that
# survives recognition rather than on an exact sentence.
OCR_EXPECTED_ANY = ("badge", "replacement", "security office")


class Reporter:
    def __init__(self) -> None:
        self.failures: list[str] = []
        self.warnings: list[str] = []

    def ok(self, stage: str, detail: str = "") -> None:
        print(f"{GREEN}  PASS{RESET}  {stage}" + (f"  {DIM}{detail}{RESET}" if detail else ""))

    def fail(self, stage: str, detail: str) -> None:
        self.failures.append(f"{stage}: {detail}")
        print(f"{RED}  FAIL{RESET}  {stage}  {detail}")

    def warn(self, stage: str, detail: str) -> None:
        self.warnings.append(f"{stage}: {detail}")
        print(f"{YELLOW}  WARN{RESET}  {stage}  {detail}")

    def section(self, name: str) -> None:
        print(f"\n{CYAN}{name}{RESET}")


async def run(args: argparse.Namespace) -> int:
    r = Reporter()
    settings = get_settings()
    cleanup: list[str] = []

    print(f"{DIM}env={settings.env}  index={settings.opensearch.index}  "
          f"llm={settings.llm.provider}:{settings.llm.model}  "
          f"embed={settings.embedding.provider}{RESET}")

    # -- 1. configuration ----------------------------------------------------
    r.section("1. Configuration")
    r.ok("settings loaded", f"fusion={settings.retrieval.fusion} k={settings.retrieval.final_k}")

    # -- 2. embedding model --------------------------------------------------
    r.section("2. Embedding model")
    try:
        from rag_core.embeddings import get_embedder

        t0 = time.perf_counter()
        embedder = get_embedder()
        load_ms = int((time.perf_counter() - t0) * 1000)
        vector = embedder.embed_query("test")
        if len(vector) != settings.embedding.dim:
            r.fail("dimension", f"got {len(vector)}, config says {settings.embedding.dim}")
            return 1
        r.ok("model loaded", f"{load_ms}ms, dim={len(vector)}")

        # A model returning near-identical vectors for unrelated text is broken
        # in a way that still indexes and still searches -- and returns garbage.
        a = embedder.embed_query("claims documentation retention")
        b = embedder.embed_query("the colour of the sky on a Tuesday")
        similarity = sum(x * y for x, y in zip(a, b))
        if similarity > 0.95:
            r.fail("discrimination", f"unrelated texts have similarity {similarity:.3f}")
        else:
            r.ok("discriminates between texts", f"unrelated similarity={similarity:.3f}")
    except Exception as e:
        r.fail("embedding model", str(e))
        return 1

    # -- 3. OpenSearch -------------------------------------------------------
    r.section("3. OpenSearch")
    try:
        from rag_core.search import ChunkIndexer, IndexAdmin, get_client

        client = get_client()
        info = client.info()
        r.ok("reachable", f"v{info['version']['number']} ({info['version'].get('distribution', '')})")

        admin = IndexAdmin(client, settings.opensearch)
        if not admin.exists():
            admin.create(dim=settings.embedding.dim)
            r.ok("index created", settings.opensearch.index)
        else:
            r.ok("index exists", str(admin.stats()))
    except Exception as e:
        r.fail("opensearch", str(e))
        return 1

    # -- 4. Tika -------------------------------------------------------------
    r.section("4. Tika extraction")
    try:
        from rag_core.extraction import TikaClient

        tika = TikaClient(settings.tika)
        if not tika.health():
            r.fail("tika", f"unreachable at {settings.tika.url}")
            return 1
        pages = tika.extract_pages(TEST_DOCUMENT.encode("utf-8"), TEST_FILENAME, "text/plain")
        if not pages or EXPECTED_IN_CONTEXT not in " ".join(p.text for p in pages):
            r.fail("extraction", "expected text not found in Tika output")
            return 1
        r.ok("extracted", f"{len(pages)} page(s), {sum(len(p.text) for p in pages)} chars")
    except Exception as e:
        r.fail("tika", str(e))
        return 1

    # -- 5. OCR service ------------------------------------------------------
    r.section("5. OCR service")
    ocr = None
    if args.skip_ocr:
        r.warn("ocr", "skipped (--skip-ocr)")
    elif not settings.ocr.enabled:
        r.warn("ocr", "disabled by config (RAG_OCR__ENABLED)")
    else:
        try:
            from rag_core.extraction import OCRClient

            candidate = OCRClient(settings.ocr)
            if candidate.health():
                ocr = candidate
                r.ok("reachable", settings.ocr.url)
            else:
                r.fail("ocr", f"unreachable at {settings.ocr.url} "
                              f"(start it: docker compose up -d ocr)")
        except Exception as e:
            r.fail("ocr", str(e))

    # -- 6. ingest -----------------------------------------------------------
    r.section("6. Ingest pipeline")
    try:
        from rag_core.extraction import IngestPipeline

        pipeline = IngestPipeline(
            settings, tika, ocr, embedder,
            ChunkIndexer(client, settings.opensearch), admin,
        )
        result = pipeline.ingest_bytes(
            TEST_DOCUMENT.encode("utf-8"), TEST_FILENAME,
            source_uri=TEST_URI, content_type="text/plain",
            metadata={"smoke_test": True}, refresh=True,
        )
        if not result.ok:
            r.fail("ingest", f"{result.errors}")
            return 1
        cleanup.append(stable_id(TEST_URI))
        r.ok("indexed", f"{result.chunks_indexed} chunks  {result.timings_ms}")
    except Exception as e:
        r.fail("ingest", str(e))
        return 1

    # -- 7. retrieval --------------------------------------------------------
    r.section("7. Retrieval")
    doc_id = stable_id(TEST_URI)
    retriever = None
    try:
        from rag_core.search import HybridRetriever

        retriever = HybridRetriever(client, embedder, settings.retrieval, settings.opensearch)

        # Each leg is checked independently. If only one works, fusion still
        # returns results and the failure hides -- until relevance quietly
        # degrades in production.
        bm25_hits = retriever.bm25(QUESTION, 10)
        if any(h.doc_id == doc_id for h in bm25_hits):
            r.ok("bm25 found the document", f"{len(bm25_hits)} hits")
        else:
            r.fail("bm25", "test document not in results")

        knn_hits = retriever.knn(QUESTION, 10)
        if any(h.doc_id == doc_id for h in knn_hits):
            r.ok("knn found the document", f"{len(knn_hits)} hits")
        else:
            r.fail("knn", "test document not in results")

        hits = retriever.retrieve(QUESTION)
        if not hits:
            r.fail("fusion", "no results")
            return 1
        top = hits[0]
        if top.doc_id != doc_id:
            r.warn("fusion", f"test document was not rank 1 (got {top.filename!r})")
        if not any(EXPECTED_IN_CONTEXT in h.text for h in hits):
            r.fail("fusion", f"{EXPECTED_IN_CONTEXT!r} absent from retrieved context")
        else:
            r.ok("fusion returned the answer text",
                 f"{len(hits)} hits, top score {top.score:.4f}, via {top.retrievers}")

        # Filters must actually filter, or entitlement-based filtering later is
        # silently a no-op.
        filtered = retriever.retrieve(QUESTION, filters={"doc_id": "definitely-not-a-real-doc"})
        if filtered:
            r.fail("filters", f"filter ignored: {len(filtered)} hits for a bogus doc_id")
        else:
            r.ok("filters are applied")
    except Exception as e:
        r.fail("retrieval", str(e))
        return 1

    # -- 8. generation -------------------------------------------------------
    r.section("8. LLM generation")
    llm = None
    if args.skip_llm:
        r.warn("llm", "skipped (--skip-llm)")
    else:
        try:
            from rag_core.llm import get_llm
            from rag_core.rag import RagPipeline

            llm = get_llm()
            rag = RagPipeline(retriever, llm, settings)
            answer = await rag.answer(QUESTION)

            if not answer.answer.strip():
                r.fail("generation", "empty answer")
            else:
                r.ok("answered", f"{answer.timings_ms}  model={answer.model}")
                print(f"{DIM}        Q: {QUESTION}{RESET}")
                print(f"{DIM}        A: {answer.answer.strip()[:300]}{RESET}")

                # The end-to-end assertion: the fact from the document must
                # appear in the answer. This is what proves RAG worked, rather
                # than the model answering from its own weights.
                if EXPECTED_IN_CONTEXT in answer.answer.lower():
                    r.ok("answer contains the grounded fact", repr(EXPECTED_IN_CONTEXT))
                else:
                    r.fail("grounding", f"{EXPECTED_IN_CONTEXT!r} missing from the answer")

                if answer.cited_indices:
                    r.ok("answer cites sources", str(answer.cited_indices))
                else:
                    r.warn("citations", "model produced no [n] markers; check the system prompt")
        except Exception as e:
            r.fail("llm", str(e))

    # -- 9. OCR end-to-end ---------------------------------------------------
    r.section("9. OCR end-to-end (page with no text layer)")
    if ocr is None:
        r.warn("ocr e2e", "skipped, OCR service not available")
    elif not OCR_FIXTURE.is_file():
        r.warn("ocr e2e", f"fixture missing; run: python ops/make_scan_fixture.py")
    else:
        try:
            data = OCR_FIXTURE.read_bytes()

            # First prove Tika alone cannot read it. If Tika returns real text,
            # the fixture has a text layer and the test proves nothing.
            tika_pages = tika.extract_pages(data, OCR_FIXTURE.name, "image/png")
            tika_chars = sum(len(p.text.strip()) for p in tika_pages)
            if tika_chars > 200:
                r.warn("ocr e2e", f"Tika already extracted {tika_chars} chars; "
                                  f"fixture may not be image-only")
            else:
                r.ok("fixture has no usable text layer", f"Tika got {tika_chars} chars")

            t0 = time.perf_counter()
            ocr_result = pipeline.ingest_bytes(
                data, OCR_FIXTURE.name, source_uri=OCR_URI,
                content_type="image/png", metadata={"smoke_test": True}, refresh=True,
            )
            ocr_ms = int((time.perf_counter() - t0) * 1000)

            if not ocr_result.ok:
                r.fail("ocr ingest", f"{ocr_result.errors}")
            else:
                cleanup.append(stable_id(OCR_URI))
                if ocr_result.ocr_pages < 1:
                    r.fail("ocr routing", "OCR was not triggered for a text-free page")
                else:
                    r.ok("OCR triggered and extracted text",
                         f"{ocr_result.ocr_pages} page(s), "
                         f"{ocr_result.chunks_indexed} chunks, {ocr_ms}ms")

                ocr_hits = retriever.retrieve(OCR_QUESTION, k=10)
                mine = [h for h in ocr_hits if h.doc_id == stable_id(OCR_URI)]
                if not mine:
                    r.fail("ocr retrieval", "scanned document not retrievable")
                else:
                    text = " ".join(h.text.lower() for h in mine)
                    found = [w for w in OCR_EXPECTED_ANY if w in text]
                    if found:
                        r.ok("scanned content is searchable", f"recognised {found}")
                        print(f"{DIM}        OCR text: {mine[0].text.strip()[:160]!r}{RESET}")
                    else:
                        r.fail("ocr quality",
                               f"none of {OCR_EXPECTED_ANY} recognised; got "
                               f"{mine[0].text[:120]!r}")

                    if mine[0].extraction_source != "ocr":
                        r.warn("ocr provenance",
                               f"chunk labelled {mine[0].extraction_source!r}, expected 'ocr'")
                    else:
                        r.ok("chunks tagged with OCR provenance")

                # Answering over OCR'd content is the real goal.
                if llm is not None:
                    from rag_core.rag import RagPipeline

                    ocr_answer = await RagPipeline(retriever, llm, settings).answer(OCR_QUESTION)
                    print(f"{DIM}        Q: {OCR_QUESTION}{RESET}")
                    print(f"{DIM}        A: {ocr_answer.answer.strip()[:220]}{RESET}")
                    if "three" in ocr_answer.answer.lower() or "3" in ocr_answer.answer:
                        r.ok("answered a question about a scanned page")
                    else:
                        r.warn("ocr answer", "expected 'three business days' in the answer")
        except Exception as e:
            r.fail("ocr e2e", str(e))

    # -- 10. HTTP API --------------------------------------------------------
    r.section("10. HTTP API + SSE streaming")
    if not args.api_url:
        r.warn("api", "skipped (pass --api-url http://localhost:8000)")
    else:
        try:
            import httpx

            base = args.api_url.rstrip("/") + "/api/v1"
            async with httpx.AsyncClient(timeout=180.0) as http:
                resp = await http.get(f"{base}/health/ready")
                body = resp.json()
                if resp.status_code == 200 and body.get("ok"):
                    r.ok("GET /health/ready", "all components ok")
                else:
                    r.fail("GET /health/ready", json.dumps(body)[:200])

                cfg = (await http.get(f"{base}/config")).json()
                r.ok("GET /config", f"{cfg.get('llm_provider')}:{cfg.get('llm_model')}")
                if "api_key" in json.dumps(cfg).lower():
                    r.fail("/config", "endpoint leaks a secret")

                sr = await http.post(f"{base}/search", json={"query": QUESTION, "k": 5})
                hits = sr.json().get("hits", [])
                if hits:
                    r.ok("POST /search", f"{len(hits)} hits in {sr.json().get('took_ms')}ms")
                else:
                    r.fail("POST /search", "no hits")

                stats = (await http.get(f"{base}/index/stats")).json()
                r.ok("GET /index/stats", json.dumps(stats))

                if args.skip_llm:
                    r.warn("POST /chat/stream", "skipped (--skip-llm)")
                else:
                    # This is the exact path the browser uses. Parsing it here
                    # proves the UI will work before you ever open it.
                    events: dict[str, int] = {}
                    tokens: list[str] = []
                    sources_seen = 0
                    async with http.stream(
                        "POST", f"{base}/chat/stream",
                        json={"question": QUESTION, "history": [], "stream": True},
                    ) as sresp:
                        if sresp.status_code != 200:
                            r.fail("POST /chat/stream", f"HTTP {sresp.status_code}")
                        else:
                            async for line in sresp.aiter_lines():
                                if not line.startswith("data:"):
                                    continue
                                try:
                                    ev = json.loads(line[5:].strip())
                                except json.JSONDecodeError:
                                    continue
                                events[ev["type"]] = events.get(ev["type"], 0) + 1
                                if ev["type"] == "sources":
                                    sources_seen = len(ev.get("sources", []))
                                elif ev["type"] == "token":
                                    tokens.append(ev.get("text", ""))
                                elif ev["type"] == "error":
                                    r.fail("stream error", ev.get("message", "")[:200])

                    streamed = "".join(tokens)
                    if events.get("sources") and sources_seen:
                        r.ok("SSE sources event", f"{sources_seen} sources, sent before tokens")
                    else:
                        r.fail("SSE sources event", "missing or empty")
                    if events.get("token", 0) > 1:
                        r.ok("SSE token stream", f"{events['token']} token events")
                    else:
                        r.fail("SSE token stream", f"only {events.get('token', 0)} token events")
                    if events.get("done"):
                        r.ok("SSE done event")
                    else:
                        r.fail("SSE done event", "never received")
                    if EXPECTED_IN_CONTEXT in streamed.lower():
                        r.ok("streamed answer is grounded", repr(EXPECTED_IN_CONTEXT))
                    else:
                        r.warn("streamed answer", f"{EXPECTED_IN_CONTEXT!r} not in streamed text")
        except Exception as e:
            r.fail("api", f"{e}  (is the API running on {args.api_url}?)")

    # -- cleanup -------------------------------------------------------------
    if llm is not None:
        await llm.aclose()

    if not args.keep:
        removed = 0
        for did in cleanup:
            try:
                removed += admin.delete_by_doc_id(did)
            except Exception as e:
                r.warn("cleanup", str(e))
        print(f"\n{DIM}cleaned up {removed} test chunks{RESET}")
    else:
        print(f"\n{DIM}left test documents in the index: {cleanup}{RESET}")

    # -- verdict -------------------------------------------------------------
    print()
    if r.failures:
        print(f"{RED}FAILED{RESET} — {len(r.failures)} problem(s):")
        for f in r.failures:
            print(f"  {RED}x{RESET} {f}")
        if r.warnings:
            print(f"{YELLOW}{len(r.warnings)} warning(s):{RESET}")
            for w in r.warnings:
                print(f"  {YELLOW}!{RESET} {w}")
        return 1

    print(f"{GREEN}ALL STAGES PASSED{RESET}")
    if r.warnings:
        print(f"{YELLOW}{len(r.warnings)} warning(s):{RESET}")
        for w in r.warnings:
            print(f"  {YELLOW}!{RESET} {w}")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description="End-to-end smoke test")
    p.add_argument("--skip-llm", action="store_true", help="do not call the model endpoint")
    p.add_argument("--skip-ocr", action="store_true", help="do not exercise the OCR service")
    p.add_argument("--api-url", default="", help="also test the HTTP API, e.g. http://localhost:8000")
    p.add_argument("--keep", action="store_true", help="leave test documents indexed")
    return asyncio.run(run(p.parse_args()))


if __name__ == "__main__":
    sys.exit(main())
